/**
 * Prefer WebP sibling when present in /public (generated by scripts/optimize-brand-images.mjs).
 */
export function preferWebpSrc(src: string): string {
  if (!src.startsWith("/")) return src;
  if (src.endsWith(".webp")) return src;

  const base = src.replace(/\.(png|jpe?g)$/i, "");
  if (base === src) return src;
  return `${base}.webp`;
}

export function pictureSources(src: string): { webp: string; fallback: string } {
  return { webp: preferWebpSrc(src), fallback: src };
}
